version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_URL: ${REACT_APP_URL}
      REACT_APP_NAME: ${REACT_APP_NAME}
      REACT_APP_VERSION: ${REACT_APP_VERSION}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - '/app/node_modules'

  backend:
    build: ./backend
    ports:
      - "${API_PORT}:3001"
    environment:
      MONGO_HOST: mongoDB
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
    depends_on:
      - mongoDB
    volumes:
      - ./backend:/api
      - '/api/node_modules'

  mongoDB:
    image: mongo:6
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGODB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo:/data/db

volumes:
  mongo:
  frontend:
  backend:

